/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2020-01-27 12:39:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.res.incl;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1580128432000L));
    _jspx_dependants.put("jar:file:/D:/Fourker_s/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer id=\"bottom-footer\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row wow fdeInUp\">\r\n");
      out.write("      <div class=\"col-md-4 col-sm-4 col-xs-12\"> \r\n");
      out.write("        <!--copyright-->\r\n");
      out.write("        <p class=\"copyright\">© 2018 <a href=\"https://devfloat.net/\">Grit</a>. All rights reserved</p>\r\n");
      out.write("        <!--/copyright--> \r\n");
      out.write("      </div>\r\n");
      out.write("      <!--bottom nav-->\r\n");
      out.write("      <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("        <nav class=\"bottom-nav\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("            <li><a href=\"#\">Privacy</a></li>\r\n");
      out.write("            <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("            <li><a href=\"#\">Pricing</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--/bottom nav--> \r\n");
      out.write("      \r\n");
      out.write("      <!--powered by-->\r\n");
      out.write("      <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("        <ul class=\"social-link\">\r\n");
      out.write("          <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("          <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("          <li><a href=\"#\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("          <li><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--/powered by--> \r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> \r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script> \r\n");
      out.write("<!-- Include all compiled plugins (below), or include individual files as needed --> \r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/bootstrap.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/SmoothScroll.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.isotope.js\"></script> \r\n");
      out.write("<script src=\"/js/owl.carousel.js\"></script> \r\n");
      out.write("<script src=\"/js/jquery.waypoints.min.js\"></script> \r\n");
      out.write("<!-- Javascripts\r\n");
      out.write("    ================================================== --> \r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/main.js\"></script> \r\n");
      out.write("<script src=\"/js/wow.min.js\"></script> \r\n");
      out.write("<script>\r\n");
      out.write("    jQuery(document).ready(function( $ ) {\r\n");
      out.write("        $('.counter').counterUp({\r\n");
      out.write("            delay: 10,\r\n");
      out.write("            time: 1000\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script> \r\n");
      out.write("<script>\r\n");
      out.write("new WOW().init();\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
